# base_train.yaml
path: datasets/synthetic
train: images/train
val: images/val
test: images/test

names:
  0: Plastic bag & wrapper
  1: Cigarette
  2: Bottle
  3: Bottle cap
  4: Can
  5: Other plastic
  6: Carton
  7: Cup