# ===== task & io =====
task: detect
mode: train
model: yolo11m.pt                 # COCO-pretrained (or yolo11s.pt if VRAM tight)
data: configs/base_train.yaml
project: runs/yolo11
name: base_train
cache: true
workers: 8
device: 0

# ===== schedule =====
epochs: 100
patience: 10
batch: 8
imgsz: 1024

# ===== optimizer =====
optimizer: adamw
lr0: 0.002
lrf: 0.01                         # cosine final LR = 1% of lr0
weight_decay: 0.01
warmup_epochs: 3
warmup_momentum: 0.8
warmup_bias_lr: 0.1

# ===== augmentation (strong for synthetic) =====
degrees: 5.0
translate: 0.10
scale: 0.50
shear: 2.0
perspective: 0.0005
hsv_h: 0.015
hsv_s: 0.70
hsv_v: 0.70
mosaic: 1.0
mixup: 0.15
copy_paste: 0.30
fliplr: 0.50
flipud: 0.00
close_mosaic: 10                  # taper strong augs in last 10 epochs
rect: false
